[package]
name = "xor_filter"
version = "0.1.0"
authors = ["jeremysalwen"]
edition = "2018"

[dependencies]
num = "0.2.0"
linked_hash_set = "0.1.3"

[dev-dependencies]
statrs = "0.12.0"
more-asserts = "0.2.1"
bolero = "0.4.1"
