[package]
name = "xor_filter"
version = "0.1.0"
authors = ["jeremysalwen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
len-trait = "0.6.1"
linked_hash_set = "0.1.3"